config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "relationships#index"
  post '/relationships/guest_sign_in', to: 'relationships#new_guest'
  resources :groups, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      get :join, :member
      delete :quit
    end
    collection do
      get :list, :search
    end
    resources :tweets do
      resources :likes, only: [:create, :destroy] do
        member do
          get :list
        end
      end
    end
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get :list, :owner
      delete :purge
    end
    collection do
      get :search
    end
  end
  resources :relationships, only: [:index, :create, :destroy] do
    member do
      get :following, :follower
    end
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :group
  belongs_to :user
  has_one_attached :image
  has_many :likes, dependent: :destroy

  validates :content, presence: true, unless: :was_attached?,
                      length_with_wide_char: { maximum: 400 }

  def was_attached?
    self.image.attached?
  end

  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :new, :edit]
  before_action :set_group
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  before_action :right_bar, only: [:index, :show]

  def index
    @tweets = @group.tweets.with_attached_image.order("created_at DESC").includes(:user, :likes, :image_attachment, user: { avator_attachment: :blob })
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = @group.tweets.new(tweet_params)
    if @tweet.save
      redirect_to group_tweets_path(@group)
    else
      @tweets = @group.tweets.includes(:user)
      render :new
    end
  end

  def show
  end

  def edit
    unless user_signed_in? && current_user.id == @tweet.user_id
      redirect_to root_path
    end
  end

  def update
    if @tweet.update(tweet_params)
      redirect_to group_tweets_path(@group)
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @tweet.user_id
      @tweet.destroy
      redirect_to group_tweets_path(@group)
    else
      render :index
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end

  def set_tweet
    @tweet = @group.tweets.find(params[:id])
  end

  def right_bar
    @groups = Group.select("groups.*, COUNT(group_users.id) users_count").left_joins(:group_users).group("groups.id").order("users_count desc").limit(20)
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
  def tweet_time(time)
    time < 1.week.ago ? l(time) : time_ago_in_words(time)
  end
end

app/views/tweets/_left_bar.html.erb
<div class="left-bar-container">
  <div class="left-bar-upper">
    <div class="left-bar-home left-bar-element">
      <%= link_to root_path do %>
        <i class="fa fa-home fa-fw"></i>&nbsp;&nbsp;ホーム
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="left-bar-profile left-bar-element">
        <%= link_to user_path(current_user.id) do %>
          <i class="fa fa-user fa-fw"></i>&nbsp;&nbsp;プロフィール
        <% end %>
      </div>
      <div class="left-bar-friend left-bar-element">
        <%= link_to following_relationship_path(current_user) do %>
          <i class="fa fa-user-friends fa-fw"></i>&nbsp;&nbsp;フレンド
        <% end %>
      </div>
    <% else %>
      <div class="left-bar-profile left-bar-element">
        <%= link_to root_path do %>
          <i class="fa fa-user fa-fw"></i>&nbsp;&nbsp;プロフィール
        <% end %>
      </div>
      <div class="left-bar-friend left-bar-element">
        <%= link_to root_path do %>
          <i class="fa fa-user-friends fa-fw"></i>&nbsp;&nbsp;フレンド
        <% end %>
      </div>
    <% end %>
    <div class="left-bar-group-list left-bar-element">
      <%= link_to list_groups_path do %>
        <i class="fa fa-search fa-fw"></i>&nbsp;&nbsp;探す
      <% end %>
    </div>
    <div class="left-bar-making-group left-bar-element">
      <%= link_to new_group_path do %>
        <i class="fa fa-plus-circle fa-fw"></i>&nbsp;&nbsp;グループを作る
      <% end %>
    </div>
  </div>
  <% if user_signed_in? %>
    <div class="left-bar-lower">
      <div class="left-bar-group-title">
        <%= link_to list_user_path(current_user.id) do %>
          <i class="fa fa-users fa-fw"></i>&nbsp;&nbsp;あなたのグループ
        <% end %>
      </div>
      <div class="left-bar-groups">
          <% current_user.groups.each do |group| %>
            <div class="left-bar-group">
              <div class="left-bar-group-name">
                <%= link_to group.name, group_tweets_path(group) %>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  <% end %>
</div>

<%# タブレット表示時 %>
<div class="left-bar-container-responsive">
  <div class="left-bar-upper">
    <div class="left-bar-home left-bar-element">
      <%= link_to root_path do %>
        <i class="fa fa-home fa-fw"></i>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="left-bar-profile left-bar-element">
        <%= link_to user_path(current_user.id) do %>
          <i class="fa fa-user fa-fw"></i>
        <% end %>
      </div>
      <div class="left-bar-friend left-bar-element">
        <%= link_to following_relationship_path(current_user) do %>
          <i class="fa fa-user-friends fa-fw"></i>
        <% end %>
      </div>
    <% else %>
      <div class="left-bar-profile left-bar-element">
        <%= link_to root_path do %>
          <i class="fa fa-user fa-fw"></i>
        <% end %>
      </div>
      <div class="left-bar-friend left-bar-element">
        <%= link_to root_path do %>
          <i class="fa fa-user-friends fa-fw"></i>
        <% end %>
      </div>
    <% end %>
    <div class="left-bar-group-list left-bar-element">
      <%= link_to list_groups_path do %>
        <i class="fa fa-search fa-fw"></i>
      <% end %>
    </div>
    <div class="left-bar-making-group left-bar-element">
      <%= link_to new_group_path do %>
        <i class="fa fa-plus-circle fa-fw"></i>
      <% end %>
    </div>
    <% if user_signed_in? %>
      <div class="left-bar-group-title">
        <%= link_to list_user_path(current_user.id) do %>
          <i class="fa fa-users fa-fw"></i>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/tweets/_main_chat.html.erb
<div class="main-chat-container">
  <div class="main-chat-header">
    <div class="main-chat-header-upper">
      <div class="main-chat-header-upper-left">
        <%= link_to @group.name, group_path(@group.id) %>
      </div>
      <div class="main-chat-header-upper-right"></div>
    </div>
    <div class="main-chat-header-lower">
      <div class="main-chat-header-lower-left">
        <%= link_to new_group_tweet_path do %>
          <i class="fa fa-pen-alt fa-fw"></i>&nbsp;&nbsp;ツイート
        <% end %>
      </div>
      <div id="group-quit-open">
        <i class="fa fa-user-slash fa-fw"></i>&nbsp;&nbsp;退会する
      </div>
      <div id="group-quit-modal">
        <div class="group-quit-confirmation">
          <div class="group-quit-sentence">
            本当にこのグループを退会しますか？
          </div>
          <div class="group-quit-btn">
            <div id="group-quit-btn-cancel">
              キャンセル
            </div>
            <div class="group-quit-btn-action">
              <%= link_to(quit_group_path(@group), method: :delete) do %>
                <i class="fa fa-user-slash fa-fw"></i>&nbsp;&nbsp;退会する
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="tweets">
    <%= render partial: 'tweet', collection: @tweets %>
  </div>
</div>

app/views/tweets/_right_bar.html.erb
<div class="right-bar-container">
  <div class="right-bar-upper">
    <div class="right-bar-group-search">
      <%= form_with(url: search_groups_path, local: true, method: :get, class: "right-bar-group-search-form") do |f| %>
        <%= f.text_field :keyword, placeholder: "グループ検索", class: "right-bar-group-search-input" %>
        <label class="right-bar-group-search-btn">
          <i class="fa fa-search"></i>
          <%= f.submit class: "hidden" %>
        </label>
      <% end %>
    </div>
  </div>
  <div class="right-bar-lower">
    <div class="right-bar-title">
      グループ Top20
    </div>
    <div class="right-bar-groups">
      <% @groups.each do |group| %>
        <% if user_signed_in? %>
          <% unless GroupUser.exists?(group_id: group.id, user_id: current_user.id) %>
            <div class="right-bar-group-no-participation">
              <%= link_to group_path(group.id) do %>
                <div class="right-bar-group">
                  <div class="right-bar-group-icon">
                    <i class="fa fa-users-slash fa-fw"></i>
                  </div>
                  <div class="right-bar-group-name">
                    <%= group.name %>
                  </div>
                </div>
              <% end %>
            </div>
          <% else %>
            <div class="right-bar-group-participation">
              <%= link_to group_path(group.id) do %>
                <div class="right-bar-group">
                  <div class="right-bar-group-icon">
                    <i class="fa fa-users fa-fw"></i>
                  </div>
                  <div class="right-bar-group-name">
                    <%= group.name %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% else %>
          <div class="right-bar-group-no-participation">
            <%= link_to group_path(group.id) do %>
              <div class="right-bar-group">
                <div class="right-bar-group-icon">
                  <i class="fa fa-users-slash fa-fw"></i>
                </div>
                <div class="right-bar-group-name">
                  <%= group.name %>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/tweets/_tweet.html.erb
<div class="tweet">
  <div class="tweet-container">
    <div class="tweet-upper">
      <div class="tweet-upper-left">
        <%= link_to(user_path(tweet.user.id)) do %>
          <div class="tweet-upper-avator">
            <% if tweet.user.avator.attached? %>
              <%= image_tag tweet.user.avator %>
            <% else %>
              <%= image_tag "human.dummy.png" %>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="tweet-upper-right">
        <div class="tweet-upper-right-upper">
          <div class="tweet-user">
            <%= link_to tweet.user.nickname, user_path(tweet.user_id) %>
          </div>
          <div class="tweet-date">
            <%= tweet_time(tweet.created_at) %>
          </div>
        </div>
        <div class="tweet-group">
          <%= link_to tweet.group.name, group_path(tweet.group.id) %>
        </div>
      </div>
    </div>
    <div class="tweet-lower">
      <%= link_to group_tweet_path(tweet.group, tweet.id) do %> 
        <div class="tweet-content">
          <%= safe_join(tweet.content.split("\n"),tag(:br)) %>
          <%= image_tag tweet.image, class: 'tweet-image' if tweet.image.attached? %>
        </div>
      <% end %>
      <div id="likes-button<%= tweet.id %>">
        <%= render partial: "likes/like", locals: { tweet: tweet, like: @like } %>
      </div>
    </div>
  </div>
</div>

app/views/tweets/edit.html.erb
<div class="tweet-form">
  <%= form_with model: [@group, @tweet], local: true do |f| %>
    <div class="tweet-form-container">
      <div class="tweet-form-wrapper">
        <div class="tweet-form-upper">
          <%= f.text_area :content, class: "tweet-form-upper-input input-text", placeholder: '何を伝える？', autofocus: true %>
        </div>
        <div class="input-text-count"></div>
        <div id="image-list"></div>
          <%= image_tag @tweet.image if @tweet.image.attached? %>
        <div class="tweet-form-lower">
          <label class="tweet-form-lower-left">
            <div class="tweet-form-lower-left-icon">
              <span class="camera-icon"><i class="fa fa-camera-retro fa-fw"></i></span>
              <%= f.file_field :image, class: 'hidden' %>
            </div>
          </label>
          <div class="tweet-form-right">
            <div class="tweet-form-submit">
              <%= f.submit '編集する', class: "tweet-form-submit-btn" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tweets/index.html.erb
<div class="wrapper">
  <div class="left-bar">
    <%= render "left_bar" %>
  </div>
  <div class="main">
    <%= render "main_chat" %>
  </div>
  <div class="right-bar">
    <%= render "right_bar"%>
  </div>
</div>

app/views/tweets/new.html.erb
<div class="tweet-form">
  <%= form_with model: [@group, @tweet], local: true do |f| %>
    <div class="tweet-form-container">
      <div class="tweet-form-wrapper">
        <div class="tweet-form-upper">
          <%= f.text_area :content, class: "tweet-form-upper-input input-text", placeholder: '何を伝える？', autofocus: true %>
        </div>
        <div class="input-text-count"></div>
        <div id="image-list"></div>
        <div class="tweet-form-lower">
          <label class="tweet-form-lower-left">
            <div class="tweet-form-lower-left-icon">
              <span class="camera-icon"><i class="fa fa-camera-retro fa-fw"></i></span>
              <%= f.file_field :image, class: 'hidden' %>
            </div>
          </label>
          <div class="tweet-form-right">
            <div class="tweet-form-submit">
              <%= f.submit 'ツイート', class: "tweet-form-submit-btn" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/tweets/show.html.erb
<div class="wrapper">
  <div class="left-bar">
    <%= render "left_bar" %>
  </div>
  <div class="main">
    <div class="tweet-show-container">
      <div class="tweet-show-upper">
        <div class="tweet-show-upper-left"></div>
        <div class="tweet-show-upper-right">
          <% if user_signed_in? && @tweet.user_id == current_user.id%>
            <div class="tweet-show-upper-right-edit">
              <%= link_to(edit_group_tweet_path(@group, @tweet.id)) do %>
                <i class="fa fa-wrench fa-fw"></i>編集する
              <% end %>
            </div>
            <div id="tweet-delete-open">
              <i class="fa fa-trash-alt fa-fw"></i>削除する
            </div>
          <% end %>
        </div>
        <div id="tweet-delete-modal">
          <div class="tweet-delete-confirmation">
            <div class="tweet-delete-sentence">
              本当にこのツイートを削除しますか？
            </div>
            <div class="tweet-delete-btn">
              <div id="tweet-delete-btn-cancel">
                キャンセル
              </div>
              <div class="tweet-delete-btn-action">
                <%= link_to(group_tweet_path(@group, @tweet.id), method: :delete) do %>
                  <i class="fa fa-trash-alt fa-fw"></i>削除する
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <% if user_signed_in? && @tweet.user_id == current_user.id%>
          <div id="tweet-show-upper-right-responsive">
            <i class="fa fa-ellipsis-h fa-fw"></i>
          </div>
          <nav class="tweet-show-nav">
            <ul class="tweet-show-nav-menu-ul">
              <li class="tweet-show-nav-menu-li">
                <%= link_to(edit_group_tweet_path(@group, @tweet.id)) do %>
                  <i class="fa fa-wrench fa-fw"></i>編集する
                <% end %>
              </li>
              <li class="tweet-show-nav-menu-li" id="responsive-tweet-delete">
                <i class="fa fa-trash-alt fa-fw"></i>削除する
              </li>
            </ul>
          </nav>
        <% end %>
      </div>
      <div class="tweet-show-lower">
        <div class="tweet-show-lower-upper">
          <div class="tweet-show-lower-left">
            <%= link_to(user_path(@tweet.user_id)) do %>
              <div class="tweet-show-avator">
                <% if @tweet.user.avator.attached? %>
                  <%= image_tag @tweet.user.avator %>
                <% else %>
                  <%= image_tag "human.dummy.png" %>
                <% end %>
              </div>
            <% end %>
          </div>
          <div class="tweet-show-lower-right">
            <div class="tweet-show-lower-user">
              <%= link_to @tweet.user.nickname, user_path(@tweet.user_id) %>
            </div>
            <div class="tweet-show-lower-group">
              <%= link_to @group.name, group_path(@group) %>
            </div>
          </div>
        </div>
        <div class="tweet-show-lower-content">
          <%= safe_join(@tweet.content.split("\n"),tag(:br)) %>
          <%= image_tag @tweet.image, class: "tweet-show-lower-image" if @tweet.image.attached? %>
        </div>
        <div class="tweet-show-lower-date">
          <%= l @tweet.created_at, format: :long %>
        </div>
        <div class="tweet-show-likes">
          <div id="likes-show-button<%= @tweet.id %>">
            <%= render partial: "likes/like_show", locals: { tweet: @tweet, like: @like } %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="right-bar">
    <%= render "right_bar" %>
  </div>
</div>