config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "relationships#index"
  post '/relationships/guest_sign_in', to: 'relationships#new_guest'
  resources :groups, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      get :join, :member
      delete :quit
    end
    collection do
      get :list, :search
    end
    resources :tweets do
      resources :likes, only: [:create, :destroy] do
        member do
          get :list
        end
      end
    end
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get :list, :owner
      delete :purge
    end
    collection do
      get :search
    end
  end
  resources :relationships, only: [:index, :create, :destroy] do
    member do
      get :following, :follower
    end
  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_users
  has_many :users, through: :group_users, dependent: :destroy
  has_many :tweets, dependent: :destroy
  belongs_to :user

  validates :name, presence: true, uniqueness: true,
                  length_with_wide_char: { maximum: 70 }
  validates :content, length_with_wide_char: { maximum: 200 }

  def self.search(search)
    if search != ""
      Group.where('name LIKE(?)', "%#{search}%")
    else
      Group.all
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_group, only: [:show, :edit, :update, :destroy, :join, :quit, :member]
  before_action :right_bar, only: [:show, :member]

  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = current_user.owned_groups.new(group_params)
    @group.users << current_user
    if current_user.save
      redirect_to group_tweets_path(@group)
    else
      render :new
    end
  end

  def show
    @tweets = @group.tweets.with_attached_image.order("created_at DESC").includes(:user, :likes, :image_attachment, user: { avator_attachment: :blob })
  end

  def edit
    unless user_signed_in? && current_user.id == @group.user_id
      redirect_to root_path
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_path(@group.id)
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to list_groups_path
  end

  def list
    @groups = Group.select("groups.*, COUNT(group_users.id) users_count").left_joins(:group_users).group("groups.id").order("users_count desc").includes(:group_users, :user, :users)
    @newgroups = Group.order("created_at DESC").limit(20)
  end

  def join
    if !@group.users.include?(current_user)
      @group.users << current_user
      redirect_to group_tweets_path(@group)
    end
  end

  def quit
    @group.users.delete(current_user)
    redirect_to root_path
  end

  def search
    @groups = Group.search(params[:keyword]).select("groups.*, COUNT(group_users.id) users_count").left_joins(:group_users).group("groups.id").order("users_count desc").includes(:group_users, :user, :users)
    @newgroups = Group.order("created_at DESC").limit(20)
  end

  def member
    @users = @group.users.with_attached_avator
  end

  private
  
  def group_params
    params.require(:group).permit(:name, :content, user_ids: [])
  end

  def set_group
    @group = Group.find(params[:id])
  end

  def right_bar
    @groups = Group.select("groups.*, COUNT(group_users.id) users_count").left_joins(:group_users).group("groups.id").order("users_count desc").limit(20)
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_group_list.html.erb
<div class="wrapper">
  <div class="left-bar">
    <%= render "/tweets/left_bar" %>
  </div>
  <div class="main">
    <div class="group-list">
      <div class="group-list-header">
        <div class="group-list-header-upper">
          <div class="group-list-header-upper-left">
            <%= link_to "グループ", list_groups_path %>
          </div>
          <div class="group-list-header-upper-right">
            <%= link_to "ユーザー", search_users_path %>
          </div>
        </div>
        <div class="group-list-header-lower">
          <div class="group-list-header-group-search">
            <%= form_with(url: search_groups_path, local: true, method: :get, class: "group-list-header-group-search-form") do |f| %>
              <%= f.text_field :keyword, placeholder: "グループを検索", class: "group-list-header-group-search-input" %>
              <label class="group-list-header-group-search-btn">
                <i class="fa fa-search"></i>
                <%= f.submit class: "hidden" %>
              </label>
            <% end %>
          </div>
        </div>
      </div>
      <div class="group-list-main">
        <% @groups.each do |group| %>
          <div class="group-list-main-container">
            <div class="group-list-main-upper">
              <div class="group-list-main-upper-left">
                <div class="group-list-main-users-member">
                  <%= link_to "#{group.users.length}参加中", member_group_path(group) %>
                </div>
              </div>
              <div class="group-list-main-upper-right">
                <% if user_signed_in? %>
                  <% unless GroupUser.exists?(group_id: group.id, user_id: current_user.id) %>
                    <div class="group-list-main-no-participation">
                      <%= link_to '参　加', join_group_path(group) %>
                    </div>
                  <% else %>
                    <div class="group-list-main-participation">
                      <%= link_to '参加中', group_tweets_path(group) %>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="group-list-main-center">
              <%= link_to(group_path(group.id)) do %>
                <div class="group-list-main-group-name">
                  <%= group.name%>
                </div>
                <div class="group-list-main-group-content">
                  <%= group.content %>
                </div>
              <% end %>
            </div>
            <div class="group-list-main-lower">
                <%= link_to(user_path(group.user_id)) do %>
                  <div class="group-list-main-lower-left">
                      <div class="group-list-main-group-owner-icon">
                        <i class="fa fa-user-shield fa-fw"></i>
                      </div>
                      <div class="group-list-main-group-owner-name">
                        <%= group.user.nickname %>
                      </div>
                  </div>
                <% end %>
              <div class="group-list-main-lower-right">
                <div class="group-list-main-group-birthday">
                  <i class="fa fa-history fa-fw"></i><%= l group.created_at %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="right-bar">
    <div class="group-list-right-bar-container">
      <div class="group-list-right-bar-title">
        新着グループ
      </div>
      <div class="group-list-right-bar-groups">
        <% @newgroups.each do |group| %>
          <% if user_signed_in? %>
            <% unless GroupUser.exists?(group_id: group.id, user_id: current_user.id) %>
              <div class="right-bar-group-no-participation">
                <%= link_to group_path(group.id) do %>
                  <div class="right-bar-group">
                    <div class="right-bar-group-icon">
                      <i class="fa fa-users-slash fa-fw"></i>
                    </div>
                    <div class="right-bar-group-name">
                      <%= group.name %>
                    </div>
                  </div>
                <% end %>
              </div>
            <% else %>
              <div class="right-bar-group-participation">
                <%= link_to group_path(group.id) do %>
                  <div class="right-bar-group">
                    <div class="right-bar-group-icon">
                      <i class="fa fa-users fa-fw"></i>
                    </div>
                    <div class="right-bar-group-name">
                      <%= group.name %>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% else %>
            <div class="right-bar-group-no-participation">
              <%= link_to group_path(group.id) do %>
                <div class="right-bar-group">
                  <div class="right-bar-group-icon">
                    <i class="fa fa-users-slash fa-fw"></i>
                  </div>
                  <div class="right-bar-group-name">
                    <%= group.name %>
                  </div>
                </div>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/groups/_member_list.html.erb
<div class="group-member-main-container">
  <div class="group-member-main-upper">
    <div class="group-member-main-upper-left"></div>
    <div class="group-member-main-upper-right">
      <% if user_signed_in? %>
        <% unless current_user.id == user.id %>
          <%= render partial: "/relationships/follow_button", locals: { user: user } %>
        <% else %>
          <div class="group-member-main-upper-right-edit">
            <%= link_to(edit_user_path(user.id)) do %>
              <i class="fa fa-wrench fa-fw"></i>アカウント編集
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <%= link_to(user_path(user.id)) do %>
    <div class="group-member-main-lower">
      <div class="group-member-main-lower-left">
        <div class="group-member-avator">
          <% if user.avator.attached? %>
            <%= image_tag user.avator %>
          <% else %>
            <%= image_tag "human.dummy.png" %>
          <% end %>
        </div>
      </div>
      <div class="group-member-main-lower-right">
        <div class="group-member-user-nickname">
          <%= user.nickname %>
        </div>
        <div class="group-member-user-introduction">
          <%= user.introduction %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/edit.html.erb
<div class="group-form">
  <%=form_with model: @group, local: true do |f|%>
    <div class="group-form-container">
      <div class="group-form-wrapper">
        <div class="group-form-upper">
          <div class="group-name-edit">
            <%= @group.name %>
          </div>
        </div>
        <div class="group-form-upper">
          <%= f.text_area :content, class:"group-content-form-upper-input group-content-input-text", placeholder:"どんなグループ？", autofocus: true %>
        </div>
        <div class="group-content-input-count"></div>
        <div class="group-form-lower">
          <div class="group-form-lower-left"></div>
          <div class="group-form-lower-right">
            <%= f.submit 'グループを編集する', class: "group-form-submit-btn" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/list.html.erb
<%= render "group_list" %>

app/views/groups/member.html.erb
<div class="wrapper">
  <div class="left-bar">
    <%= render "/tweets/left_bar" %>
  </div>
  <div class="main">
    <div class="group-member-header">
      <div class="group-member-header-left">
      <%= link_to @group.name, group_path(@group.id) %>
      </div>
      <div class="group-member-header-right">
        <%= "のメンバー(#{@group.users.length}参加中)" %>
      </div>
    </div>
    <div class="group-member-main">
      <% @users.each do |user| %>
        <%= render partial: "member_list", locals: { user: user } %>
      <% end %>
    </div>
  </div>
  <div class="right-bar">
    <%= render "/tweets/right_bar" %>
  </div>
</div>

app/views/groups/new.html.erb
<div class="group-form">
  <%=form_with model: @group, local: true do |f|%>
    <div class="group-form-container">
      <div class="group-form-wrapper">
        <div class="group-form-upper">
          <%= f.text_area :name, class:"group-name-form-upper-input group-name-input-text", placeholder:"グループの名前は？", autofocus: true %>
        </div>
        <div class="group-name-input-count"></div>
        <div class="group-form-upper">
          <%= f.text_area :content, class:"group-content-form-upper-input group-content-input-text", placeholder:"どんなグループ？" %>
        </div>
        <div class="group-content-input-count"></div>
        <div class="group-form-lower">
          <div class="group-form-lower-left"></div>
          <div class="group-form-lower-right">
            <%= f.submit 'グループを作る', class: "group-form-submit-btn" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/groups/search.html.erb
<%= render "group_list" %>

app/views/groups/show.html.erb
<div class="wrapper">
  <div class="left-bar">
    <%= render "/tweets/left_bar" %>
  </div>
  <div class="main">
    <div class="group-show-main">
      <div class="group-show-header">
        <div class="group-show-header-container">
          <div class="group-show-header-upper">
            <div class="group-show-header-upper-left">
              <div class="group-show-header-users-member">
                <%= link_to "#{@group.users.length}参加中", member_group_path(@group) %>
              </div>
            </div>
            <% if user_signed_in? && current_user.id == @group.user_id %>
              <div class="group-show-header-upper-center">
                <div class="group-show-header-upper-center-edit">
                  <%= link_to(edit_group_path(@group.id)) do %>
                    <i class="fa fa-wrench fa-fw"></i>グループを編集
                  <% end %>
                </div>
                <div id="group-delete-open">
                  <i class="fa fa-trash-alt fa-fw"></i>グループを削除
                </div>
              </div>
              <div id="group-delete-modal">
                <div class="group-delete-confirmation">
                  <div class="group-delete-sentence">
                    本当にこのグループを削除しますか？
                  </div>
                  <div class="group-delete-btn">
                    <div id="group-delete-btn-cancel">
                      キャンセル
                    </div>
                    <div class="group-delete-btn-action">
                      <%= link_to(group_path(@group.id), method: :delete) do %>
                        <i class="fa fa-trash-alt fa-fw"></i>グループを削除
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
            <div class="group-show-header-upper-right">
              <% if user_signed_in? && current_user.id == @group.user_id %>
                <div id="group-show-header-upper-responsive">
                  <i class="fa fa-ellipsis-h fa-fw"></i>
                </div>
                <nav class="group-show-nav">
                  <ul class="group-show-nav-menu-ul">
                    <li class="group-show-nav-menu-li">
                      <%= link_to(edit_group_path(@group.id)) do %>
                        <i class="fa fa-wrench fa-fw"></i>グループを編集
                      <% end %>
                    </li>
                    <li class="group-show-nav-menu-li" id="responsive-group-delete">
                      <i class="fa fa-trash-alt fa-fw"></i>グループを削除
                    </li>
                  </ul>
                </nav>
              <% end %>
              <% if user_signed_in? %>
                <% unless GroupUser.exists?(group_id: @group.id, user_id: current_user.id) %>
                  <div class="group-show-header-no-participation">
                    <%= link_to '参　加', join_group_path(@group) %>
                  </div>
                <% else %>
                  <div class="group-show-header-participation">
                    <%= link_to '参加中', group_tweets_path(@group) %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="group-show-header-center">
            <div class="group-show-header-group-name">
              <%= @group.name%>
            </div>
            <div class="group-show-header-group-content">
              <%= @group.content %>
            </div>
          </div>
          <div class="group-show-header-lower">
              <%= link_to(user_path(@group.user_id)) do %>
                <div class="group-show-header-lower-left">
                    <div class="group-show-header-group-owner-icon">
                      <i class="fa fa-user-shield fa-fw"></i>
                    </div>
                    <div class="group-show-header-group-owner-name">
                      <%= @group.user.nickname %>
                    </div>
                </div>
              <% end %>
            <div class="group-show-header-lower-right">
              <div class="group-show-header-group-birthday">
                <i class="fa fa-history fa-fw"></i><%= l @group.created_at %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="group-show-main-tweets">
        <%= render partial: '/tweets/tweet', collection: @tweets %>
      </div>
    </div>
  </div>
  <div class="right-bar">
    <%= render "/tweets/right_bar" %>
  </div>
</div>