config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "relationships#index"
  post '/relationships/guest_sign_in', to: 'relationships#new_guest'
  resources :groups, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      get :join, :member
      delete :quit
    end
    collection do
      get :list, :search
    end
    resources :tweets do
      resources :likes, only: [:create, :destroy] do
        member do
          get :list
        end
      end
    end
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get :list, :owner
      delete :purge
    end
    collection do
      get :search
    end
  end
  resources :relationships, only: [:index, :create, :destroy] do
    member do
      get :following, :follower
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, presence: true

  has_many :group_users
  has_many :groups, through: :group_users
  has_many :tweets
  has_many :owned_groups, class_name: "Group"

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverse_of_relationships, source: :user

  has_many :likes, dependent: :destroy
  has_one_attached :avator

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: :edit
  before_action :set_user, only: [:show, :edit, :update, :list, :owner, :purge]
  before_action :right_bar, only: [:show, :list, :owner,:search]

  def show
    @tweets = @user.tweets.with_attached_image.order("created_at DESC").includes(:group, :likes, :image_attachment)
  end

  def edit
    unless user_signed_in? && current_user.id == @user.id
      redirect_to root_path
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(current_user.id)
    else
      render :edit
    end
  end

  def list
    @groupLists = @user.groups.select("groups.*, COUNT(group_users.id) users_count").left_joins(:group_users).group("groups.id").order("users_count desc").includes(:group_users, :users, :user)
  end

  def owner
    @groupOwners = @user.owned_groups.select("groups.*, COUNT(group_users.id) users_count").left_joins(:group_users).group("groups.id").order("users_count desc").includes(:group_users, :users)
  end

  def purge
    @user.avator.purge
    redirect_to edit_user_path(current_user.id)
  end

  def search
    @q = User.ransack(params[:q])
    @users = @q.result.with_attached_avator
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :introduction, :email, :avator)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def right_bar
    @groups = Group.select("groups.*, COUNT(group_users.id) users_count").left_joins(:group_users).group("groups.id").order("users_count desc").limit(20)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="account-page">
  <div class="account-page-title">
    アカウントの編集
  </div>
  <%= form_with model: @user, url: user_path, local: true do |f|%>
    <div class="account-page-container">
      <div class="account-page-wrapper">
        <div class="field-input account-page-input-avator">
          <label class="account-page-input-avator-btn">
            <div id="avator-list"></div>
            <% if @user.avator.attached? %>
              <%= image_tag @user.avator, class: "accont-page-input-avator-edit" %>
              <%= f.file_field :avator, class: 'hidden' %>
              <%= link_to(purge_user_path(current_user.id), method: :delete) do %>
                <i class="fa fa-trash-alt fa-fw"></i>プロフィール画像を削除する
              <% end %>
            <% else %>
              <%= image_tag "human.dummy.png", class: "human-dummy" %>
              <%= f.file_field :avator, class: 'hidden' %>
              <%= link_to(purge_user_path(current_user.id), method: :delete) do %>
                <i class="fa fa-trash-alt fa-fw"></i>プロフィール画像を削除する
              <% end %>
            <% end %>
          </label>
        </div>
        <div class="field-input account-page-input-name">
          <%= f.label :nickname, class: "field-label" %>
          <%= f.text_field :nickname, placeholder: "ニックネーム", autofocus: true %>
        </div>
        <div class="field-input account-page-input-introduction">
          <%= f.label :introduction, class: "field-label" %>
          <%= f.text_area :introduction, class: "introduction-area", placeholder: "自己紹介" %>
        </div>
        <div class="field-input account-page-input-email">
          <%= f.label :email, class: "field-label" %>
          <%= f.email_field :email, placeholder: "メールアドレス" %>
        </div>
        <div class="account-page-btn">
          <div class="account-page-btn-right"></div>
          <div class="account-page-btn-left">
            <%= f.submit "編集する", class: 'account-page-submit-btn'%>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/list.html.erb
<div class="wrapper">
  <div class="left-bar">
    <%= render "/tweets/left_bar" %>
  </div>
  <div class="main">
    <div class="user-group-list">
      <div class="user-group-list-header">
        <div class="user-group-list-header-upper">
          <%= @user.nickname %>のグループ
        </div>
        <div class="user-group-list-header-lower">
          <div class="user-group-list-header-lower-left">
            <%= link_to "参加中", list_user_path(@user.id) %>
          </div>
          <div class="user-group-list-header-lower-right">
            <%= link_to "オーナー", owner_user_path(@user.id) %>
          </div>
        </div>
      </div>
      <div class="user-group-list-main">
        <% @groupLists.each do |group| %>
          <div class="group-list-main-container">
            <div class="group-list-main-upper">
              <div class="group-list-main-upper-left">
                <div class="group-list-main-users-member">
                  <%= link_to "#{group.users.length}参加中", member_group_path(group) %>
                </div>
              </div>
              <div class="group-list-main-upper-right">
                <% if user_signed_in? %>
                  <% unless GroupUser.exists?(group_id: group.id, user_id: current_user.id) %>
                    <div class="group-list-main-no-participation">
                      <%= link_to '参　加', join_group_path(group) %>
                    </div>
                  <% else %>
                    <div class="group-list-main-participation">
                      <%= link_to '参加中', group_tweets_path(group) %>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="group-list-main-center">
              <%= link_to(group_path(group.id)) do %>
                <div class="group-list-main-group-name">
                  <%= group.name%>
                </div>
                <div class="group-list-main-group-content">
                  <%= group.content %>
                </div>
              <% end %>
            </div>
            <div class="group-list-main-lower">
                <%= link_to(user_path(group.user_id)) do %>
                  <div class="group-list-main-lower-left">
                      <div class="group-list-main-group-owner-icon">
                        <i class="fa fa-user-shield fa-fw"></i>
                      </div>
                      <div class="group-list-main-group-owner-name">
                        <%= group.user.nickname %>
                      </div>
                  </div>
                <% end %>
              <div class="group-list-main-lower-right">
                <div class="group-list-main-group-birthday">
                  <i class="fa fa-history fa-fw"></i><%= l group.created_at %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="right-bar">
    <%= render "/tweets/right_bar" %>
  </div>
</div>

app/views/users/owner.html.erb
<div class="wrapper">
  <div class="left-bar">
    <%= render "/tweets/left_bar" %>
  </div>
  <div class="main">
    <div class="user-group-list">
      <div class="user-group-list-header">
        <div class="user-group-list-header-upper">
          <%= @user.nickname %>のグループ
        </div>
        <div class="user-group-list-header-lower">
          <div class="owner-group-list-header-lower-left">
            <%= link_to "参加中", list_user_path(@user.id) %>
          </div>
          <div class="owner-group-list-header-lower-right">
            <%= link_to "オーナー", owner_user_path(@user.id) %>
          </div>
        </div>
      </div>
      <div class="user-group-list-main">
        <% @groupOwners.each do |group| %>
          <div class="group-list-main-container">
            <div class="group-list-main-upper">
              <div class="group-list-main-upper-left">
                <div class="group-list-main-users-member">
                  <%= link_to "#{group.users.length}参加中", member_group_path(group) %>
                </div>
              </div>
              <div class="group-list-main-upper-right">
                <% if user_signed_in? %>
                  <% unless GroupUser.exists?(group_id: group.id, user_id: current_user.id) %>
                    <div class="group-list-main-no-participation">
                      <%= link_to '参　加', join_group_path(group) %>
                    </div>
                  <% else %>
                    <div class="group-list-main-participation">
                      <%= link_to '参加中', group_tweets_path(group) %>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="group-list-main-center">
              <%= link_to(group_path(group.id)) do %>
                <div class="group-list-main-group-name">
                  <%= group.name%>
                </div>
                <div class="group-list-main-group-content">
                  <%= group.content %>
                </div>
              <% end %>
            </div>
            <div class="group-list-main-lower">
                <%= link_to(user_path(group.user_id)) do %>
                  <div class="group-list-main-lower-left">
                      <div class="group-list-main-group-owner-icon">
                        <i class="fa fa-user-shield fa-fw"></i>
                      </div>
                      <div class="group-list-main-group-owner-name">
                        <%= group.user.nickname %>
                      </div>
                  </div>
                <% end %>
              <div class="group-list-main-lower-right">
                <div class="group-list-main-group-birthday">
                  <i class="fa fa-history fa-fw"></i><%= l group.created_at %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="right-bar">
    <%= render "/tweets/right_bar" %>
  </div>
</div>

app/views/users/search.html.erb
<div class="wrapper">
  <div class="left-bar">
    <%= render "/tweets/left_bar" %>
  </div>
  <div class="main">
    <div class="user-search">
      <%= search_form_for @q, url: search_users_path do |f| %>
        <div class="user-search-header">
          <div class="user-search-header-upper">
            <div class="user-search-header-upper-left">
              <%= link_to "グループ", list_groups_path %>
            </div>
            <div class="user-search-header-upper-right">
              <%= link_to "ユーザー", search_users_path %>
            </div>
          </div>
          <div class="user-search-header-lower">
            <div class="user-search-header-search">
              <%= f.search_field :nickname_or_introduction_cont, placeholder: "ユーザーを検索", class: "users-search-textarea" %>
              <label class="user-search-header-search-btn">
                <i class="fa fa-search"></i>
                <%= f.submit class: "hidden" %>
              </label>
            </div>
          </div>
        </div>
        <div class="user-search-main">
          <% if @users.present? %>
            <div class="search-users">
              <% @users.each do |user| %>
                <%= render partial: "/groups/member_list", locals: { user: user } %>
              <% end %>
            </div>
          <% else %>
            <div class="user-empty-message">
              一致するユーザーがいません。
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="right-bar">
    <%= render "/tweets/right_bar" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="wrapper">
  <div class="left-bar">
    <%= render "/tweets/left_bar" %>
  </div>
  <div class="main">
    <div class="user-show-main">
      <div class="user-show-header">
        <div class="user-show-header-upper">
          <div class="user-show-header-upper-left"></div>
          <div class="user-show-header-upper-right">
            <% if user_signed_in? %>
              <%= render partial: "/relationships/follow_button", locals: { user: @user } %>
            <% end %>
            <% if user_signed_in? && current_user.id == @user.id %>
              <div class="user-show-header-upper-right-edit">
                <%= link_to(edit_user_path(@user.id)) do %>
                  <i class="fa fa-wrench fa-fw"></i>アカウントを編集
                <% end %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="user-show-header-center">
          <div class="user-show-header-center-left">
            <div class="user-show-avator">
              <% if @user.avator.attached? %>
                <%= image_tag @user.avator %>
              <% else %>
                <%= image_tag "human.dummy.png" %>
              <% end %>
            </div>
          </div>
          <div class="user-show-header-center-left">
            <div class="user-show-nickname">
              <%= @user.nickname %>
            </div>
            <div class="user-show-introduction">
              <%= @user.introduction %>
            </div>
          </div>
        </div>
        <div class="user-show-header-lower">
          <div class="user-show-header-lower-follow-member">
            <%= render partial: "/relationships/follow_number" %>
          </div>
          <div class="user-show-header-lower-group">
            <div class="user-show-header-lower-group-participation">
              <%= link_to "#{@user.groups.length}グループ", list_user_path(@user.id) %>
            </div>
            <div class="user-show-header-lower-group-owner">
              <%= link_to "#{@user.owned_groups.length}オーナー", owner_user_path(@user.id) %>
            </div>
          </div>
        </div>
      </div>
      <div class="user-show-main-tweets">
        <%= render partial: '/tweets/tweet', collection: @tweets %>
      </div>
    </div>
  </div>
  <div class="right-bar">
    <%= render "/tweets/right_bar" %>
  </div>
</div>