config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "relationships#index"
  post '/relationships/guest_sign_in', to: 'relationships#new_guest'
  resources :groups, only: [:new, :create, :show, :edit, :update, :destroy] do
    member do
      get :join, :member
      delete :quit
    end
    collection do
      get :list, :search
    end
    resources :tweets do
      resources :likes, only: [:create, :destroy] do
        member do
          get :list
        end
      end
    end
  end
  resources :users, only: [:show, :edit, :update] do
    member do
      get :list, :owner
      delete :purge
    end
    collection do
      get :search
    end
  end
  resources :relationships, only: [:index, :create, :destroy] do
    member do
      get :following, :follower
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroupTalk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <header>
      <div class="header">
        <div class="header-left">
          <%= link_to 'GroupTalk', root_path, class: "header-title" %>
        </div>
        <div class="header-right">
          <% if user_signed_in? %>
            <div class="user-nickname">
              <%= link_to current_user.nickname, user_path(current_user.id), class: "user-nickname" %>
            </div>
            <div id="logout-open">
              ログアウト
            </div>
          <% else %>
            <%= link_to 'ゲストログイン(閲覧用)', relationships_guest_sign_in_path, method: :post, class: "guest-login" %>
            <%= link_to 'ログイン', new_user_session_path, class: "login" %>
            <%= link_to '新規登録', new_user_registration_path, class: "sign-up" %>
          <% end %>
        </div>
        <div id="logout-modal">
          <div class="logout-confirmation">
            <div class="logout-sentence">
              本当にログアウトしますか？
            </div>
            <div class="logout-btn">
              <div id="logout-btn-cancel">
                キャンセル
              </div>
              <div class="logout-btn-action">
                <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>
              </div>
            </div>
          </div>
        </div>
        <div id="header-right-responsive">
          <i class="fa fa-bars fa-fw"></i>
        </div>
        <% if user_signed_in? %>
          <nav class="header-nav">
            <ul class="header-nav-menu-ul">
              <li class="header-nav-menu-li">
                <%= link_to 'プロフィール', user_path(current_user.id) %>
              </li>
              <li class="header-nav-menu-li" id="responsive-logout-open">
                ログアウト
              </li>
            </ul>
          </nav>
        <% else %>
          <nav class="header-nav">
            <ul class="header-nav-menu-ul">
              <li class="header-nav-menu-li">
                <%= link_to 'ゲストログイン(閲覧用)', relationships_guest_sign_in_path, method: :post %>
              </li>
              <li class="header-nav-menu-li responsive-login">
                <%= link_to 'ログイン', new_user_session_path %>
              </li>
              <li class="header-nav-menu-li">
                <%= link_to '新規登録', new_user_registration_path %>
              </li>
            </ul>
          </nav>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
      <div class="footer-elements">
        <div class="footer-home">
          <%= link_to root_path do %>
            <i class="fa fa-home fa-fw"></i>
          <% end %>
        </div>
        <% if user_signed_in? %>
          <div class="footer-profile">
            <%= link_to user_path(current_user.id) do %>
              <i class="fa fa-user fa-fw"></i>
            <% end %>
          </div>
        <% else %>
          <div class="footer-profile">
            <%= link_to root_path do %>
              <i class="fa fa-user fa-fw"></i>
            <% end %>
          </div>
        <% end %>
        <div class="footer-group-list">
          <%= link_to list_groups_path do %>
            <i class="fa fa-search fa-fw"></i>
          <% end %>
        </div>
        <div class="footer-making-group">
          <%= link_to new_group_path do %>
            <i class="fa fa-plus-circle fa-fw"></i>
          <% end %>
        </div>
        <% if user_signed_in? %>
          <div class="footer-group-title">
            <%= link_to list_user_path(current_user.id) do %>
              <i class="fa fa-users fa-fw"></i>
            <% end %>
          </div>
        <% end %>
      </div>
    </footer>
  </body>
</html>